### ISSUE TITLE
account.history() returns inconsistent results

### ISSUE THREAD

**Issue by cocryptominer** [bitshares/python-bitshares#118]
When I create a new Account object and call account.history(), sometime the whole set of transactions is returned, sometimes a small subset.

```
account = Account("acountname")
for h in account.history():
    print(h)
```

**Comment by clockworkgr** [comment]
Account history is dependent on the node you're connecting to.. Does the issue appear while using the SAME API node?

**Comment by cocryptominer** [comment]
The python library doesn't specify the node its connecting too. This is the whole script:
```
from bitshares.account import Account
account = Account("init0")
print(account.balances)
print(account.openorders)
for h in account.history():
    print(h)
```
Its from http://docs.pybitshares.com/en/latest/

**Comment by overdrivemachines** [comment]
I have the same issue. Here is my code:
```py
a = Account("someaccount")
history_transactions = a.history(limit=200)
i = 1
for transaction in history_transactions:
    print(i)
```
Sometimes I will get 50 results and other times I will get 100 results.
When is this going to be fixed?

**Comment by xeroc** [comment]
The reason here is:

* pybitshares connects to `node.bitshares.eu` by default
* `node.bitshares.eu` is loadbalanced with 8 backend nodes
* some of those backend nodes are setup so that they only store 100 some others only store 50 items in an accounts history.

If you need more history, you can look into the eswrapper https://eswrapper.bitshares.eu/apidocs/ (experimental) or setup your own backend node
