### ISSUE TITLE
Lost connection to node during wsconnect(): wss://node.bitshares.eu

### ISSUE THREAD

**Issue by litepresence** [bitshares/python-bitshares#89]
when I start a script and make my first call to Account(), or switch nodes and make a call to Account() I sporadically get an error regarding a node that I have NOT specified:

```
Lost connection to node during wsconnect(): wss://node.bitshares.eu (4/-1) Retrying in 6 seconds
```

This is the call:
```
account = Account(USERNAME, bitshares_instance=BitShares(node, num_retries=0))
```
I does NOT happen when calling:
```
market = Market(BitPAIR, bitshares_instance=BitShares(node, num_retries=0), mode='head')
chain = Blockchain(bitshares_instance=BitShares(node, num_retries=0), mode='head')
```

this code will force the error (it will auto break with ```sys.exit()```):

https://pastebin.com/PvxHXgv5

this may be related to issue 88, which relates to first call after creating Account() object whereas this is when creating account object.

also, when I specifically test
```
n = wss://node.bitshares.eu
chain = Blockchain(
                bitshares_instance=BitShares(n, num_retries=0), mode='head')
```

the node connects without issue.

it also connects with a /ws extension; but not with a /wss

**Comment by kohako** [comment]
I have the same issue on dexbot mac vesion. Any fix for this yet ? Thanks

**Comment by RuneStone0** [comment]
I had similar issue. It seems that in some cases you're unable to overwrite the default node. The default node is configured in storage.py. I made a temporary fix, so it at least can communicate with a working node: https://github.com/bitshares/python-bitshares/pull/115

However, this issue is still valid. Currently you cannot trust that the default node(s) is overwritten.

**Comment by xeroc** [comment]
try this
```
from bitshares.instance import set_shared_blockchain_instance

set_shared_blockchain_instance(bitshares_instance)
```

**Comment by RuneStone0** [comment]
It works, except it should be set_shared_bitshares_instance (minor typo).

But, it still seems like a work around? It should be possible trust this:

BitShares(node=BITSHARES_NODES)

**Comment by xeroc** [comment]
The reason here is that by calling the `BitShares()` class, **no** default instance is set. If you want your own one to be used as default you'll need to explicitly do so or stick with providing the instance in your calls.

That way, you can connect to different backend nodes at the same time (like, testnet+main net).
