### ISSUE TITLE
py-bitshares module on Windows

### ISSUE THREAD

**Issue by imildar** [bitshares/python-bitshares#9]
Hello, how can I install this modul to my Windows 10 machin?

**Comment by scientistnik** [comment]
error:
>scrypt-1.2.0/lib/crypto\crypto_scrypt.h(33): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

**Comment by xeroc** [comment]
Unfortunately, I don't have a windows machine around, so I cannot work on this ..
As for the error of @scientistnik, this is an error that happens when installing the dependency: scrypt.
To my knowledge there is a wheel for that dependency. Either way, it is unrelated to pybitshares.
Please let us know if you can find a solution for installing scrypt on windows!

**Comment by imildar** [comment]
i didn't find right solution to install scrypt on Windows.
it requires differents path for OpenSSL lib
![default](https://user-images.githubusercontent.com/30859071/29211175-f033ae60-7eb0-11e7-9493-289c8455991e.png)

**Comment by jhtitor** [comment]
You have to
- install scrypt via wheel
- download latest appropriate version of openssl
- extract the dlls right into the source folder of your python project :(

**Comment by holgern** [comment]
I'm the maintainer of scrypt since version 0.8.3. Since this version, I created wheels for 32Bit and 64Bit.
You can see them here: https://pypi.python.org/pypi/scrypt/
when you install scrypt with pip, it should use the wheel and there should be no need for openssl.

**Comment by jhtitor** [comment]
@holgern, thanks for letting us know.

Unfortunately, I can't confirm that scrypt wheels work out of the box. I have created a relevant https://bitbucket.org/mhallin/py-scrypt/issues/38 issue.
